// packages/react/src/PreferredSourceButton.tsx
'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import type { ButtonHTMLAttributes, CSSProperties, ReactNode } from 'react';
import { emitPsClick, isBrowser, watchAutoRenderAfterLoad } from '@opacedev/preferred-source-core';
import type { PreferredSourceTheme, PsClickDetail, SdkMode } from '@opacedev/preferred-source-core';
import { usePreferredSource } from './usePreferredSource';

const DEFAULT_LABEL = 'Add as a preferred source on Google';
const STYLE_TAG_ID = 'opace-ps-react-styles';

export type PreferredSourceVariant = 'google-default' | 'google-colours' | 'neutral';
export type PreferredSourceFallbackReason = 'blocked' | 'no-render';

export interface PreferredSourceButtonProps
  extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'onClick'> {
  theme?: PreferredSourceTheme;
  lang?: string;
  mode?: SdkMode;
  label?: string;
  variant?: PreferredSourceVariant;
  domain?: string;
  hrefFallback?: string;
  /**
   * Auto mode only: ms Google gets after a successful SDK load to paint into
   * the container before the deeplink fallback takes over. Default 4000.
   */
  renderTimeoutMs?: number;
  /** Fired when the trigger is clicked. Reports the click, never a completed add. */
  onPsClick?: (detail: PsClickDetail) => void;
  /** Fired when the component swaps to the deeplink fallback. */
  onPsFallback?: (detail: { reason: PreferredSourceFallbackReason }) => void;
  children?: ReactNode;
}

const baseStyle: CSSProperties = {
  display: 'inline-flex',
  alignItems: 'center',
  gap: '0.5em',
  boxSizing: 'border-box',
  cursor: 'pointer',
  textDecoration: 'none',
  fontFamily: 'Roboto, system-ui, -apple-system, sans-serif',
  fontSize: '0.875rem',
  fontWeight: 500,
  padding: '0.55em 1.1em',
  lineHeight: 1.2,
};

function variantStyle(variant: PreferredSourceVariant, theme: PreferredSourceTheme): CSSProperties {
  if (variant === 'google-colours') {
    return { background: '#4285F4', color: '#ffffff', border: 'none', borderRadius: 9999 };
  }
  if (variant === 'neutral') {
    return { background: 'transparent', color: 'inherit', border: '1px solid currentColor', borderRadius: 4 };
  }
  return theme === 'dark'
    ? { background: '#202124', color: '#e8eaed', border: '1px solid #5f6368', borderRadius: 4 }
    : { background: '#ffffff', color: '#1f1f1f', border: '1px solid #dadce0', borderRadius: 4 };
}

/** Hover/focus rules cannot live in inline styles; inject one deduped tag. */
const hoverCss = `
.opace-ps-btn { transition: background-color .2s ease, transform .2s ease, box-shadow .2s ease; }
.opace-ps-btn:focus-visible { outline: 2px solid #4285F4; outline-offset: 2px; }
.opace-ps-btn--google-colours:hover:not(:disabled),
.opace-ps-btn--google-colours:focus-visible {
  background: #34A853 !important;
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0,0,0,.18);
}
@media (prefers-reduced-motion: reduce) {
  .opace-ps-btn { transition: background-color .2s ease; }
  .opace-ps-btn--google-colours:hover:not(:disabled),
  .opace-ps-btn--google-colours:focus-visible { transform: none; box-shadow: none; }
}
`;

function ensureStyles(): void {
  if (!isBrowser() || document.getElementById(STYLE_TAG_ID)) return;
  const tag = document.createElement('style');
  tag.id = STYLE_TAG_ID;
  tag.textContent = hoverCss;
  document.head.appendChild(tag);
}

/**
 * Google Preferred Sources trigger for React. Manual mode by default: styled
 * button + SDK command queue, with a deeplink anchor fallback when the SDK is
 * blocked. Auto mode renders the attributed div and watches it: if Google's
 * script loads but paints nothing within renderTimeoutMs (it declines
 * silently on unrecognised origins), the deeplink fallback takes over.
 * Client component ('use client' baked in).
 */
export function PreferredSourceButton({
  theme = 'light',
  lang,
  mode = 'manual',
  label = DEFAULT_LABEL,
  variant = 'google-default',
  domain,
  hrefFallback,
  renderTimeoutMs,
  onPsClick,
  onPsFallback,
  children,
  className,
  style,
  disabled,
  ...rest
}: PreferredSourceButtonProps): ReactNode {
  const { status, open, deeplink } = usePreferredSource({ theme, lang, domain, mode });
  const autoRef = useRef<HTMLDivElement | null>(null);
  const [autoFallback, setAutoFallback] = useState<PreferredSourceFallbackReason | null>(null);

  useEffect(() => {
    ensureStyles();
  }, []);

  useEffect(() => {
    if (mode !== 'auto') return;
    const el = autoRef.current;
    if (!el) return;
    let cancelled = false;
    void watchAutoRenderAfterLoad(el, { timeoutMs: renderTimeoutMs }).then((outcome) => {
      if (cancelled || (outcome !== 'blocked' && outcome !== 'no-render')) return;
      // Emit the bubbling DOM event before React swaps the markup.
      el.dispatchEvent(
        new CustomEvent('ps-fallback', { bubbles: true, composed: true, detail: { reason: outcome } }),
      );
      onPsFallback?.({ reason: outcome });
      setAutoFallback(outcome);
    });
    return () => {
      cancelled = true;
    };
    // onPsFallback deliberately excluded from deps: the watch must run once per mount.
  }, [mode, renderTimeoutMs]);

  const handleClick = useCallback(
    (event: { currentTarget: EventTarget & HTMLElement }) => {
      if (disabled) return;
      const detail: PsClickDetail = {
        outcome: 'pending',
        mode,
        theme,
        lang,
        domain: domain ?? (isBrowser() ? location.hostname : ''),
      };
      emitPsClick(event.currentTarget, detail);
      onPsClick?.(detail);
      void open();
    },
    [disabled, mode, theme, lang, domain, onPsClick, open],
  );

  const mergedStyle: CSSProperties = { ...baseStyle, ...variantStyle(variant, theme), ...style };
  const classes = ['opace-ps-btn', `opace-ps-btn--${variant}`, className].filter(Boolean).join(' ');

  if (mode === 'auto' && autoFallback === null) {
    // Server-renderable attributed div; the SDK script must be on the page
    // before this markup for Google's documented scan to find it.
    const autoProps: Record<string, string> = { 'google-add-preferred-source-btn': '' };
    if (theme) autoProps['data-theme'] = theme;
    if (lang) autoProps['data-lang'] = lang;
    return <div ref={autoRef} className={className} {...autoProps} />;
  }

  if (status === 'blocked' || autoFallback !== null) {
    const href = hrefFallback ?? deeplink;
    return (
      <a
        className={classes}
        style={mergedStyle}
        href={href}
        target="_blank"
        rel="noopener noreferrer"
        data-ps-fallback=""
      >
        {children ?? label}
      </a>
    );
  }

  return (
    <button type="button" className={classes} style={mergedStyle} onClick={handleClick} disabled={disabled} {...rest}>
      {children ?? label}
    </button>
  );
}

// packages/vue/src/PreferredSourceButton.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import {
  buildDeeplink,
  emitPsClick,
  getSdkStatus,
  isBrowser,
  loadSdk,
  openPreferredSourceDialog,
  watchAutoRenderAfterLoad,
} from '@opacedev/preferred-source-core';
import type { PreferredSourceTheme, PsClickDetail, SdkMode, SdkStatus } from '@opacedev/preferred-source-core';

const props = withDefaults(
  defineProps<{
    theme?: PreferredSourceTheme;
    lang?: string;
    mode?: SdkMode;
    label?: string;
    variant?: 'google-default' | 'google-colours' | 'neutral';
    domain?: string;
    hrefFallback?: string;
    /** Auto mode only: ms Google gets after SDK load to paint before the deeplink fallback. Default 4000. */
    renderTimeoutMs?: number;
  }>(),
  {
    theme: 'light',
    mode: 'manual',
    label: 'Add as a preferred source on Google',
    variant: 'google-default',
  },
);

const emit = defineEmits<{
  (event: 'ps-click', detail: PsClickDetail): void;
  (event: 'ps-fallback', detail: { reason: 'blocked' | 'no-render' }): void;
}>();

const status = ref<SdkStatus>('idle');
const deeplink = ref('');
const root = ref<HTMLElement | null>(null);
const autoEl = ref<HTMLElement | null>(null);
const autoFallback = ref<'blocked' | 'no-render' | null>(null);

onMounted(() => {
  try {
    deeplink.value = props.hrefFallback ?? buildDeeplink(props.domain);
  } catch {
    deeplink.value = '';
  }
  if (props.mode === 'manual') {
    status.value = 'loading';
    void loadSdk({ mode: 'manual', theme: props.theme, lang: props.lang }).then(() => {
      status.value = getSdkStatus();
    });
  } else if (autoEl.value) {
    // The SDK loads fine on unrecognised origins and silently paints nothing,
    // so watch the container itself and swap to the deeplink on non-render.
    const el = autoEl.value;
    void watchAutoRenderAfterLoad(el, { timeoutMs: props.renderTimeoutMs }).then((outcome) => {
      if (outcome !== 'blocked' && outcome !== 'no-render') return;
      el.dispatchEvent(
        new CustomEvent('ps-fallback', { bubbles: true, composed: true, detail: { reason: outcome } }),
      );
      emit('ps-fallback', { reason: outcome });
      autoFallback.value = outcome;
    });
  }
});

const classes = computed(() => ['opace-ps-btn', `opace-ps-btn--${props.variant}`, `opace-ps-theme-${props.theme}`]);

function onClick(): void {
  const detail: PsClickDetail = {
    outcome: 'pending',
    mode: props.mode,
    theme: props.theme,
    lang: props.lang,
    domain: props.domain ?? (isBrowser() ? location.hostname : ''),
  };
  if (root.value) emitPsClick(root.value, detail);
  emit('ps-click', detail);
  void openPreferredSourceDialog({
    theme: props.theme,
    lang: props.lang,
    domain: props.domain,
  }).then((outcome) => {
    if (outcome === 'deeplink') status.value = 'blocked';
  });
}
</script>

<template>
  <div
    v-if="props.mode === 'auto' && autoFallback === null"
    ref="autoEl"
    google-add-preferred-source-btn
    :data-theme="props.theme"
    :data-lang="props.lang"
  />
  <a
    v-else-if="status === 'blocked' || autoFallback !== null"
    :class="classes"
    :href="deeplink"
    target="_blank"
    rel="noopener noreferrer"
    data-ps-fallback=""
  >
    <slot>{{ props.label }}</slot>
  </a>
  <button v-else ref="root" type="button" :class="classes" @click="onClick">
    <slot>{{ props.label }}</slot>
  </button>
</template>

<style scoped>
.opace-ps-btn {
  display: inline-flex;
  align-items: center;
  gap: 0.5em;
  box-sizing: border-box;
  cursor: pointer;
  text-decoration: none;
  font-family: Roboto, system-ui, -apple-system, sans-serif;
  font-size: 0.875rem;
  font-weight: 500;
  padding: 0.55em 1.1em;
  line-height: 1.2;
  transition: background-color 0.2s ease, transform 0.2s ease, box-shadow 0.2s ease;
}
.opace-ps-btn:focus-visible {
  outline: 2px solid #4285f4;
  outline-offset: 2px;
}
.opace-ps-btn--google-default {
  background: #ffffff;
  color: #1f1f1f;
  border: 1px solid #dadce0;
  border-radius: 4px;
}
.opace-ps-btn--google-default.opace-ps-theme-dark {
  background: #202124;
  color: #e8eaed;
  border-color: #5f6368;
}
.opace-ps-btn--google-colours {
  background: #4285f4;
  color: #ffffff;
  border: none;
  border-radius: 9999px;
}
.opace-ps-btn--google-colours:hover,
.opace-ps-btn--google-colours:focus-visible {
  background: #34a853;
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.18);
}
.opace-ps-btn--neutral {
  background: transparent;
  color: inherit;
  border: 1px solid currentColor;
  border-radius: 4px;
}
@media (prefers-reduced-motion: reduce) {
  .opace-ps-btn {
    transition: background-color 0.2s ease;
  }
  .opace-ps-btn--google-colours:hover,
  .opace-ps-btn--google-colours:focus-visible {
    transform: none;
    box-shadow: none;
  }
}
</style>
